# Generated by Django 4.2.19 on 2025-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starters',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
