# Generated by Django 4.2.19 on 2025-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_dietplan_calories_dietplan_protien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='grams',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='protien',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
